name: Bug report
description: Create a report to help us improve
title: 'Enter a summary of the issue'
labels: "bug"
body:
- type: markdown
  attributes:
    value: "**Describe the bug"
- type: textarea
  attributes:
    label: A short description about what is happening
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce the issue
  validations:
    required: true
- type: textarea
  attributes:
    label: What did you expect to happen instead?
  validations:
    required: true
- type: input
  attributes:
    label: Python Version
    placeholder: X.YY
