name: Release to PyPi
on: [workflow_dispatch]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v2
  
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
  
    - name: Install poetry 2.1.1
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install poetry==2.1.1
  
    - name: Install dependencies
      shell: bash
      run: python -m poetry install
  
    - name: Build package
      shell: bash
      run: python -m poetry build
    - name: pypi-publish
      uses: pypa/gh-action-pypi-publish@v1.12.4
